### ISSUE TITLE
Unable to use as npm dependency

### ISSUE THREAD

**Issue by danielyaa5** [oraclize/ethereum-bridge#17]
I added the github url to my npm dependency list like so

`    "node-bridge": "git://github.com/oraclize/ethereum-bridge#9dd3c06714ada82c7f006901426497c870e14c61"`

but when I try to run `node bridge` from the node_modules folder of my project, it seems that it is missing some files and errors out. It would be nice if the project supported being used as a dependency. Or even better if I could install the package globally `npm -g ethereum-bridge` and then just use the `bridge` command.

**Comment by bertani** [comment]
Hello, could you briefly describe the user case where you need ethereum-bridge to be part of your dependencies tree?
The reason why I am asking is that this is the typical way to interact with Oraclize just from within private chains and, as mentioned in the README and in the official docs, this tool is still experimental and going to be deprecated in favour of a new one (which will help a lot being it easier to set up/maintain/upgrade). The ethereum-bridge is not meant to be used as a dependency as it is not a library, but just a daemon to enable the connection from a custom rpc node to the Oraclize engine.

As for your latter suggestions, they are applicable and we will look into it, but as I said.. I wouldn't build on the top of a soon-to-be-deprecated tool (it will stop working at a certain point in the coming weeks). The new tool (stargate) will be released in a matter of days now, with all the required docs. If you are interested in trying it early to give us a feedback and study its integration with your project, that would be definitely possible and much appreciated!

**Comment by tinder-dyakobian** [comment]
Thanks it seems as though this is not really an issue then.
