### ISSUE TITLE
Is there any way to get this working with localhost?

### ISSUE THREAD

**Issue by tinder-dyakobian** [oraclize/ethereum-bridge#18]
I've tried fiddling with the javascript but everything I try fails. But I'd like to use this with a localhost query so I can use my test server.

**Comment by bertani** [comment]
Hello @tinder-dyakobian , unfortunately that's not possible as the Oraclize engine needs to reach out to datasource on the Internet. One way to workaround that while experimenting is to use a service like [localtunnel](https://localtunnel.me)!

I hope this helps.

**Comment by danielyaa5** [comment]
Hey this is awesome didnt know about local tunnel but Im having trouble getting it working on with queries. Sometimes it does and sometimes not. It doesnt seem to ever work on http://app.oraclize.it/home/test_query

**Comment by danielyaa5** [comment]
Whoops weird I removed the JSON api helper and it works now.

**Comment by bertani** [comment]
Maybe it wasn't properly formatted, what was the jsonparser query you were using?
