### ISSUE TITLE
Support for node 8

### ISSUE THREAD

**Issue by parunach** [oraclize/ethereum-bridge#26]
I am trying Oraclize with a private ethereum blockchain.

I downloaded the current version of ethereum-bridge and tried the active mode

`node bridge -H localhost:8042 -a 1`

I get the error

> Not compatible with v8.0.0 of nodejs, please use v6.9.1 or a lower version
> 
> exiting...

Can the support for latest versions be provided?

**Comment by D-Nice** [comment]
You can literally just remove/comment out this line to avoid it https://github.com/oraclize/ethereum-bridge/blob/master/bridge.js#L2

We will recheck compatibility between versions, and update the version check, the compatibility check is way too strict at the moment, and I think it should work with node 8, but it's untested yet.

**Comment by parunach** [comment]
I did that and got

> {"message":"Error: Account ","stack":"Error: Error: Account \n at deployOraclize (/Users/abc/code/blockchain/ethereum-bridge/bridge.js:525:16)\n at /Users/abc/code/blockchain/ethereum-bridge/bridge.js:425:33\n at /Users/abc/code/blockchain/ethereum-bridge/bridge.js:506:14\n at Request._callback (/Users/abc/code/blockchain/ethereum-bridge/lib/bridge-http.js:24:14)\n at Request.self.callback (/Users/abc/code/blockchain/ethereum-bridge/node_modules/request/request.js:188:22)\n at emitTwo (events.js:125:13)\n at Request.emit (events.js:213:7)\n at Request. (/Users/abc/code/blockchain/ethereum-bridge/node_modules/request/request.js:1171:10)\n at emitOne (events.js:115:13)\n at Request.emit (events.js:210:7)\n at IncomingMessage. (/Users/abc/code/blockchain/ethereum-bridge/node_modules/request/request.js:1091:12)\n at Object.onceWrapper (events.js:312:19)\n at emitNone (events.js:110:20)\n at IncomingMessage.emit (events.js:207:7)\n
> at endReadableNT (_stream_readable.js:1045:12)\n at _combinedTickCallback (internal/process/next_tick.js:102:11)"}
> 
> Exiting...

**Comment by D-Nice** [comment]
Deployed just fine for me, on node v8.1.4, running with testrpc v4.0.1 and the latest ethereum-bridge (with that versionCheck line commented out). 

What are you running it with, are you sure the account is unlocked?

**Comment by parunach** [comment]
Yes, I am running account unlocked. If it was locked, it should not crash, but complain and exit.

However, I am not running node v8.1.4, I am running v8.0.0. If you wish, I can update the node.

**Comment by D-Nice** [comment]
I am giving it a try with 8.0.0 now. In regards to using node, I highly recommend you couple it with nvm (node version manager) for your OS, so you can easily switch between different node versions due to these potential compatibility issues.

**Comment by D-Nice** [comment]
Works fine with 8.0.0 as well. How are you trying to run the bridge, with a testnet or a privatenet, and are you using testrpc?

**Comment by D-Nice** [comment]
It looks correct, but the bridge's error output indicates it can't see that account as existing on the node at all. I've recreated this on testrpc by specifying the bridge to use an account outside the account range. Are you able to interact with account[0] via the geth console, such as send transactions?

**Comment by parunach** [comment]
Let me recheck everything, I might have some error.

**Comment by parunach** [comment]
BTW, if the account is locked, can it not complain that it is locked and exit? That way a user can understand the problem and correct the running.

**Comment by D-Nice** [comment]
It does in fact

```
[2017-07-20T15:33:20.954Z] INFO deploying the oraclize connector contract...
Error: Error: Error: could not unlock signer account
```

**Comment by parunach** [comment]
I was able to get in, a mistake. However, I did not know that private blockchains require payment too. I assumed that only public ones required payment.

**Comment by D-Nice** [comment]
Glad to hear you're in. Yes, privatenets require payment still, even with privatenet ether, to simulate the mainnet environment as closely as possible!
