### ISSUE TITLE
Creation of OAR in ethereum-bridge

### ISSUE THREAD

**Issue by parunach** [oraclize/ethereum-bridge#27]
I notice from multiple users about using 

`OAR = OraclizeAddrResolverI(resolve_addr);  //add this line if you are using Oraclize in private chain environment`

and to generate the resolve_addr 

_If you are currently using private chain, you need to use the Ethereum-Bridge API to generate a OAR, which is a log listener listens to the oraclize query from private chain and connect to oraclize serivice. The following list the steps of using Ethereum-Bridge:_

> - Download the repository of Ethereum-Bridge by using git clone https://github.com/oraclize/ethereum-bridge, and execute npm install in the nodejs folder.
> - Unlock certain account (in this example we will use acoounts[0]) by using geth --unclock 0, and execute node plugin -H localhost:8545 -a 0. (make sure the account you unlock matches the account input to plugin.js)
> - Once you execute plugin.js, it will generate OAR for you to place in the constructor of your contract. After compiling it, you need to deploy it using any accounts except for the account you just unlocked.

I see that there is no plugin.js any more. All this must be outdated. How do I generate OAR to use with my private blockchain?

**Comment by marcogiglio** [comment]
Hi @parunach, those instructions are outdated. Once started, the bridge automatically generates and deploys the OAR at a deterministic address. You don't need to add anything in your contract.

**Comment by parunach** [comment]
Hi @marcogiglio, is the address 

**0xf0f20d1a90c618163d762f9f09baa003a60adeff** 

Let me know. If not, please show me how to get the address. Thanks
