### ISSUE TITLE
Missing error message when provided account is incorrect

### ISSUE THREAD

**Issue by idrabenia** [oraclize/ethereum-bridge#28]
When start application with incorrect account for instance
`node bridge.js -a 5`
I received message 
`[2017-09-01T11:02:01.190Z] ERROR 
        {"message":"Error: Account ","stack":"Error: Error: Account \n    at deployOraclize (/Users/idrabenia/Projects/opencv-test/ethereum-bridge/bridge.js:525:16)\n    at /Users/idrabenia/Projects/opencv-test/ethereum-bridge/bridge.js:425:33\n    at /Users/idrabenia/Projects/opencv-test/ethereum-bridge/bridge.js:506:14\n    at Request._callback (/Users/idrabenia/Projects/opencv-test/ethereum-bridge/lib/bridge-http.js:25:14)\n    at Request.self.callback (/Users/idrabenia/Projects/opencv-test/ethereum-bridge/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/Users/idrabenia/Projects/opencv-test/ethereum-bridge/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/Users/idrabenia/Projects/opencv-test/ethereum-bridge/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:291:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)"}`

It is not possible to understand - whats going worse from this message.

**Comment by marcogiglio** [comment]
I have merge the PR, I think we can close the issue :)
