### ISSUE TITLE
v8.4.0 of nodejs

### ISSUE THREAD

**Issue by bruciebruce** [oraclize/ethereum-bridge#31]
I am not able to downgrade my version of nodejs.
What are the issues with this package not running properly with v8.4.0 of nodejs?

Thank you,
Bruce

**Comment by marcogiglio** [comment]
Hi @bruciebruce , I have merged now a long-due fix that shoul remove that restriction. It should work now

**Comment by bruciebruce** [comment]
Okay....Looks good.  Thank you!

**Comment by D-Nice** [comment]
@bruciebruce As a quick side note, it's probably a good idea to familiarize yourself with nvm, which can be quite useful when one comes across these node version checks/issues, as it allows you to seamlessly switch between multiple different node versions. Luckily in our case, it was just an over-enforcement which was disabled.
