### ISSUE TITLE
Add `bin` directive to project.json

### ISSUE THREAD

**Issue by adisney** [oraclize/ethereum-bridge#32]
The documentation [here](https://github.com/oraclize/ethereum-bridge#active-mode) is a bit unclear in describing how to get the bridge running. The fact that it must be run from the install directory may be obvious to more experience node developers, but to node beginners it takes a bit of a logical leap.

A simple update of the documentation to indicate that you must either specify the full path to `bridge.js` or `cd` to the install directory would be very helpful.

For a more complete solution, I believe that it's possible to add a [bin directive](https://docs.npmjs.com/files/package.json#bin) to the project's `package.json`. That adds an symlink to the executable in the npm bin directory for that project, enabling node to execute the proper script when `node bridge` is executed from the command line.

**Comment by marcogiglio** [comment]
Hi @adisney, thanks for the feedback. I have updated the documentation. For the long term resolution, we will work on it in the next versions of the ethereum-bridge.
