### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by okwme** [oraclize/ethereum-bridge#33]
after triggering the oracle i get this error in the bridge terminal:
````
[2017-10-13T14:36:20.749Z] INFO sending __callback tx...
	{
    "contract_myid": "0x8e23b2147e8db2173336116c3f4fe2951e7a2b0c419fc21acb71c4f763f85c42",
    "contract_address": "0xbd31352798e53c1133c1ccf762a822e1da0a3948"
}
[2017-10-13T14:36:20.796Z] ERROR callback tx error, contract myid: 0x8e23b2147e8db2173336116c3f4fe2951e7a2b0c419fc21acb71c4f763f85c42
[2017-10-13T14:36:20.806Z] ERROR transaction hash not found, callback tx database not updated
````

**Comment by marcogiglio** [comment]
I will update the issue (and then close it) with the resolution found in the Gitter channel: the error was resolved by removing the OAR = OraclizeAddrResolverI(..), which with the last versions of the bridge is not necessary anymore.

**Comment by okwme** [comment]
unfortunately the error has started again, even with the OAR line removed : (

**Comment by okwme** [comment]
this time around the first attempt at triggering the __callback gives this warning:
```
[2017-10-13T16:34:21.828Z] WARN log with contract myid: 0x90663b48e2817a9fcd90a1b8746127fe861132029a588f971011cafcfeeb9924 was triggered, but it was already seen before, skipping event...
```

the next attempt gives the previous error

**Comment by DmitryPasenko** [comment]
Hi, have you found a solution to that?

**Comment by dpurhar27** [comment]
Just ran into this

**Comment by kimyd** [comment]
I have same issue, but it seems it is working correctly. I can get expected data from my oracle query.

**Comment by D-Nice** [comment]
kimyd do you have some example code you can share

**Comment by kimyd** [comment]
This is how I tested ..(I made my code be simple)

```
  function updateData() payable public onlyOwner {
    if(oraclize_getPrice("URL") > address(this).balance ){
      emit LogFailNewOracleQuery("Not sufficient oracle funds balance nor not approved time");
    } else {
      string memory url1 = "here is a url for GET post";
      string memory url2 = "here is another url for GET post";
      string memory url2 = "here is another url for GET post";
      bytes32 queryId;

      queryId = oraclize_query("URL", url1);      
      queryId = oraclize_query("URL", url2);      
      queryId = oraclize_query("URL", url3);      

    }
  }  

```

Every time, I call the function ,updateData, I am able to get correct resutl from url1, url2 query, but I cannot get from url3 query. I got  error message like 
` ERROR callback tx error, contract myid: 0x6808ddb2331e29c8fe2112a839c0b49058aea9af9090723112a69b6c440c1bd9`

I didn't try to testnet nor mainnet.

**Comment by UIxUX** [comment]
@kimyd Same error here! When making 3 queries from a single function.

**Comment by D-Nice** [comment]
Just tested, and 3 queries in single function work just fine. I do see some general errors in @kimyd posted code. Also, ensure you are using solc v0.4.20 or earlier, some of the new solc appears to break compatibility.

```

contract KrakenPriceTicker is usingOraclize {

    string public r1;
    string public r2;
    string public r3;

    event newOraclizeQuery(string description);
    event newKrakenPriceTicker(string price);

    bytes32 public x1;
    bytes32 public x2;
    bytes32 public x3;

    function KrakenPriceTicker() {
        oraclize_setProof(proofType_TLSNotary | proofStorage_IPFS);
        //update();
    }

    function __callback(bytes32 myid, string result, bytes proof) {
        if (msg.sender != oraclize_cbAddress()) throw;
        if (myid == x1) r1 = result;
        if (myid == x2) r2 = result;
        if (myid == x3) r3 = result;
        newKrakenPriceTicker(result);
        //update();
    }

    function update() payable {
        if (oraclize_getPrice("URL") > this.balance) {
            newOraclizeQuery("Oraclize query was NOT sent, please add some ETH to cover for the query fee");
        } else {
            newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
            x1 = oraclize_query(0, "URL", "json(https://api.kraken.com/0/public/Ticker?pair=ETHXBT).result.XETHXXBT.c.0");
            x2 = oraclize_query(0, "URL", "json(https://api.kraken.com/0/public/Ticker?pair=ETHUSD).result.XETHZUSD.c.0");
            x3 = oraclize_query(0, "URL", "json(https://api.kraken.com/0/public/Ticker?pair=XBTUSD).result.XXBTZUSD.c.0");
        }
    }

}
```

**Comment by kimyd** [comment]
@D-Nice I just simplify my original code, it is almost same as the code you just posted.  But I didn't put 0 parameter in oraclize_query, do I have to? and I am using truffle v4.1.5 , it seems it includes compiler v.0.4.21, not 0.4.20.  I would be very helpful if you can check on v.0.4.21. 
Thank you.

**Comment by D-Nice** [comment]
You will want to revert to an earlier truffle for now, that uses solc 0.4.19 or earlier. I believe Truffle v 4.13 and earlier uses appropriate solc.

**Comment by thomasvds** [comment]
Had the same issue with 4.20. For now I flush all files in the ethereum-bridge/database/tingodb folder as per this [SO post](https://ethereum.stackexchange.com/questions/40249/ethereum-bridge-warn-log-with-contract-myid-was-triggered-but-it-was-already) and it works fine.

**Comment by D-Nice** [comment]
@thomasvds If that SO post worked, then a likely workaround for you is adding the `--dev` flag upon start, which is recommended to be used when doing truffle tests.

**Comment by 1165695282** [comment]
I have the same question. And i didn't have 3 queries but only 1, and i was failed with this error.Before callback tx error i had HTTP query error too.[https://github.com/oraclize/ethereum-bridge/issues/48](url)
