### ISSUE TITLE
npm install error - sha3@1.2.0 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by sourabhniyogi** [oraclize/ethereum-bridge#36]
OS: cat /etc/redhat-release 
CentOS release 6.9 (Final)

# node --version
v8.9.1

# npm --version
5.5.1

# python --version
Python 2.6.6

# python2 --version
Python 2.7.14

# python3 --version
Python 3.6.3

Installed the following:
yum groupinstall 'Development Tools'
yum install gmp-devel

yum install avahi-compat-libdns_sd avahi-compat-libdns_sd-devel

Still no luck!

<img width="1236" alt="screen shot 2017-11-14 at 2 18 54 pm" src="https://user-images.githubusercontent.com/347067/32808140-e99405ce-c946-11e7-837b-54f2eae0e438.png">

**Comment by sourabhniyogi** [comment]
I tried with nodejs 6.x too, on a different box, didn't work!

# cat /etc/redhat-release
CentOS release 6.9 (Final)

# node --version
v6.12.0

# npm --version
3.10.10

# python --version
Python 2.6.6

# python2 --version
Python 2.7.14

# python3 --version
Python 3.6.3

Thanks!

<img width="1289" alt="screen shot 2017-11-14 at 2 33 22 pm" src="https://user-images.githubusercontent.com/347067/32808703-d71a1044-c948-11e7-8ef9-279e38cf2df6.png">

**Comment by bcshop-io** [comment]
I have the same issues.

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\nvm\v8.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v8.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\soft\ethereum-bridge-master\node_modules\sha3
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-12-06T05_42_36_023Z-debug.log

**Comment by olekon** [comment]
I have the same issues.

gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\nvm\v8.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack at emitTwo (events.js:125:13)
gyp ERR! stack at ChildProcess.emit (events.js:213:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Admin\AppData\Roaming\nvm\v8.4.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\soft\ethereum-bridge-master\node_modules\sha3
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Admin\AppData\Roaming\npm-cache_logs\2017-12-06T05_42_36_023Z-debug.log

**Comment by D-Nice** [comment]
Tried on both a Windows 7 x64 machine and also Debian Sid amd64, both with nodejs v8.9.2 and npm v5.5.1, it installed without issues. Tried on new VMs as well, to check that it isn't some dependency missing. 

Please follow instructions for your distro: https://nodejs.org/en/download/package-manager/

And ensure you have build tools for building native modules!

**Comment by D-Nice** [comment]
Could you let me know if installing via yarn avoids the issue?

**Comment by AdamJLemmon** [comment]
There seem to be several reports of similar issues, unable to nail down your exact case however. Please have a look if this link can be of any help: https://github.com/phusion/node-sha3/issues/27

**Comment by pelsasser** [comment]
I ran into this issue and solved it with `sudo apt-get install build-essential`

**Comment by Tang-xun** [comment]
I have same issues , but on mac , would you some one solved it on mac ?

**Comment by Tang-xun** [comment]
I have same issue , but on mac , some one solved it ?

**Comment by D-Nice** [comment]
@Tang-xun Could you try by just installing the ethereum-bridge as a global npm package

npm i -g ethereum-bridge

**Comment by rrubo** [comment]
Having the same issue on Windows.

**Comment by D-Nice** [comment]
The likely solution here is install missing build-essentials, or make/gcc/g++ for most cases.
