### ISSUE TITLE
Context-name is not handled correctly on public testnets

### ISSUE THREAD

**Issue by bertani** [oraclize/ethereum-bridge#38]
This should match the actual network name on public testnets too, in order for the randomds auth proof to be verifiable.

https://github.com/oraclize/ethereum-bridge/blob/a438d248fcca2130fd1d118f0c5caa066e3a1ac0/bridge.js#L898

**Comment by D-Nice** [comment]
I believe this commit fixes this?

https://github.com/oraclize/ethereum-bridge/commit/f0262fe49ecbdf9e036520ce31a6f23e9efffb8c
