### ISSUE TITLE
not possible to run 2 queries in 1 TX

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [oraclize/ethereum-bridge#40]
hey, thank you for this tool.
Unfortunately when I am trying to run 2 "oraclize_query" in 1 TX, it failed, but when I run only 1, after kick the second one it works...

**Comment by D-Nice** [comment]
Just tested this, appears to work fine with 2 URL queries being called serially in a single tx, using ethereum-bridge both master and 2018_3_updates branches.

**Comment by vitaliy-kuzmich** [comment]
Thank you for response. Did you try to run it in constructor ? Anyway, I can't repeat it, because I can't run bridge anymore on current node version.

**Comment by vitaliy-kuzmich** [comment]
if constructor can handle 2 queries, please close this issue, it might something was wrong at my side.

**Comment by D-Nice** [comment]
The queries weren't directly in the constructor, but were called via function calls from the constructor. I will close for now.
