### ISSUE TITLE
Push version 0.5.5 on npm registry

### ISSUE THREAD

**Issue by julesGoullee** [oraclize/ethereum-bridge#43]
It's not possible to install last package, the current latest on npm is: 0.5.4-alpha-1, compatible with node v6.9.1 maximum

**Comment by D-Nice** [comment]
The npm package is not officially supported by us, a third-party created it. Simply git pull from this repo for the latest version. We will see about having ownership of that npm repo handed over to us if many are using it.

**Comment by julesGoullee** [comment]
https://www.npmjs.com/package/ethereum-bridge You can see around 10 download peer day. You need to get ownership of this package, https://www.npmjs.com/~habdelra will be a hackers or hacked and many user download corrupt code, it's your responsability

**Comment by D-Nice** [comment]
Thanks for notifying us, shortly after this was mentioned we did take care of this (May 2018) and were given access to the repo amicably by the previous maintainer that wasn't related to us.
