### ISSUE TITLE
Callback tx error after oraclize query

### ISSUE THREAD

**Issue by dpurhar27** [oraclize/ethereum-bridge#44]
Hey guys, after sending the query to oraclize, when its calling __callback function, it instead runs into this error. It's been working fine for awhile, and its just started happening. I'm using Truffle and Ganache. There is a closed version of this question but I tried the suggested solution of removing 'OAR = "..."' from the contract and it didn't stop this error. Thanks for any help! 

`[2017-10-13T14:36:20.749Z] INFO sending __callback tx...
	{
    "contract_myid": "0x8e23b2147e8db2173336116c3f4fe2951e7a2b0c419fc21acb71c4f763f85c42",
    "contract_address": "0xbd31352798e53c1133c1ccf762a822e1da0a3948"
}
[2017-10-13T14:36:20.796Z] ERROR callback tx error, contract myid: 0x8e23b2147e8db2173336116c3f4fe2951e7a2b0c419fc21acb71c4f763f85c42`

**Comment by D-Nice** [comment]
Are you running with the --dev flag? If not enable --dev, it's recommended to be used with truffle & ganache, or any unit test case where ganache may revert blockchain state.
