### ISSUE TITLE
Unable to make REST service call using oraclize_query deployed on in same environment as Ethereum Network and Bridge

### ISSUE THREAD

**Issue by mandritac** [oraclize/ethereum-bridge#46]
Hi,
I have successfully called webservices residing on internet using Oraclize, but when I am trying to call a REST service which is deployed locally on the same network where my ethereum network & bridge has been setup, it fails.

Doesn't oraclize support API calls which are not available on internet as mentioned in issue#https://github.com/oraclize/ethereum-bridge/issues/18?
Ethereurm bridge has been installed on private blockchain and using broadcast mode to make the API calls. Hosted on Ubuntu machine.
Using Truffle to test the smart contract(attached).

Thanks,
[TestOraclizeCall.txt](https://github.com/oraclize/ethereum-bridge/files/1947480/TestOraclizeCall.txt)

**Comment by D-Nice** [comment]
Even though your network and bridge are running locally, the purpose of the bridge is to connect your normally private/local network, with the Oraclize service, which is a remote service. Therefore, even in this case, the Oraclize service can only see what is exposed to the rest of the internet. 

You can expose local APIs by using https://localtunnel.github.io/www/ as the issue you mentioned states.

**Comment by mandritac** [comment]
Thanks for the response, however I have one more problem I tried installing and using localtunnel but I can only access internet though corporate proxy firewall(enabled with NTLM authentication). So can we use local tunnel with proxy settings? Or is there an alternate of localtunnel which can use proxy settings before connecting to internet?

Thanks.
