### ISSUE TITLE
HTTP query error& callback tx error

### ISSUE THREAD

**Issue by 1165695282** [oraclize/ethereum-bridge#48]
Hi,guys!when i run my contract which mainly do some compute off-chain with oraclize on localhost, and return the compute result to the chain, the error message feedback.Any one help me!!!!Thanks for your help!
`[2018-04-26T13:48:12.434Z] ERROR HTTP query error
	[
    "ConnectionError"
]
[2018-04-26T13:48:12.436Z] INFO sending __callback tx...
	{
    "contract_myid": "0xab3bf2627a4d39f1c15806d47a8cf89c48a0ea0628e323ff4b12e94760b2d26c",
    "contract_address": "0x9ccf301b2bd8d42e6240418bc9ae1f9472ffcb68"
}
[2018-04-26T13:48:12.495Z] ERROR callback tx error, contract myid: 0xab3bf2627a4d39f1c15806d47a8cf89c48a0ea0628e323ff4b12e94760b2d26c
	{
    "message": "VM Exception while processing transaction: revert",
    "stack": [
        "Error: VM Exception while processing transaction: revert",
        "    at Object.InvalidResponse (/home/zyx/ethereum-bridge-master/node_modules/web3/lib/web3/errors.js:38:16)",
        "    at /home/zyx/ethereum-bridge-master/node_modules/web3/lib/web3/requestmanager.js:86:36",
        "    at XMLHttpRequest.request.onreadystatechange (/home/zyx/ethereum-bridge-master/node_modules/web3/lib/web3/httpprovider.js:118:13)",
        "    at XMLHttpRequestEventTarget.dispatchEvent (/home/zyx/ethereum-bridge-master/node_modules/xhr2/lib/xhr2.js:64:18)",
        "    at XMLHttpRequest._setReadyState (/home/zyx/ethereum-bridge-master/node_modules/xhr2/lib/xhr2.js:354:12)",
        "    at XMLHttpRequest._onHttpResponseEnd (/home/zyx/ethereum-bridge-master/node_modules/xhr2/lib/xhr2.js:509:12)",
        "    at IncomingMessage.<anonymous> (/home/zyx/ethereum-bridge-master/node_modules/xhr2/lib/xhr2.js:469:24)",
        "    at emitNone (events.js:91:20)",
        "    at IncomingMessage.emit (events.js:185:7)",
        "    at endReadableNT (_stream_readable.js:974:12)",
        "    at _combinedTickCallback (internal/process/next_tick.js:80:11)",
        "    at process._tickCallback (internal/process/next_tick.js:104:9)"
    ]
}`

**Comment by mandritac** [comment]
Are you trying to call a service hosted on localhost?

**Comment by D-Nice** [comment]
You are not querying the computation datasource in the correct manner. The first issue, which will affect any Oraclize datasource query, is that you're querying localhost, while Oraclize runs as a remote service, and when you ask it to check localhost, you are asking it to check its own localhost and not yours. If you still wish to use some API etc... that's only available locally, you should be able to use https://localtunnel.github.io/www/ 

However, in your case there's another issue, in that you are using the computation datasource incorrectly. As the computation archive, you have entered a localhost path to a python file. That is incorrect usage, the datasource expects an IPFS multihash, which points to a zipped archive, that contains a Dockerfile, and any corresponding scripts/files the Docker container that will run expects to use. 

Please refer to the relevant documentation here: https://docs.oraclize.it/#data-sources-computation

And some examples that may help you better understand how it's supposed to look and work: https://github.com/oraclize/ethereum-examples/tree/master/solidity/computation-datasource

**Comment by 1165695282** [comment]
@mandritac Yes,I hosted my python file execute computation on var/www,  and try to run it off-chain and then return the result to test net(currently)

**Comment by 1165695282** [comment]
@D-Nice ok, I will try later.Thanks a lot ^_^

**Comment by 1165695282** [comment]
@D-Nice Now i have put the python file execute computation on the cloud server, and the HTTP query error has solved, but it still reported callback tx error.

**Comment by D-Nice** [comment]
@1165695282 is the file accompanied by a Dockerfile, within a zipped archive, and hosted on IPFS?

**Comment by samvid25** [comment]
I have the same issue even when I'm trying to query IPFS using Oraclize.
