### ISSUE TITLE
What is the behaviour of --dev?

### ISSUE THREAD

**Issue by kievu** [oraclize/ethereum-bridge#52]
Ok, I had this headaching problem for almost 1 week without understanding why.
Here are simple queries (taken from 'http://app.oraclize.it/' test queries) I want to run with Oraclize
```
  event LogNewOraclizeQuery(string description);
  event LogResult(string price);

  function getResult() external payable {
    if (oraclize_getPrice("URL") > this.balance) {
      LogNewOraclizeQuery("Oraclize query was NOT sent, please add some ETH to cover for the query fee");
    }
     else {
      LogNewOraclizeQuery("Oraclize query was sent, standing by for the answer..");
      oraclize_query("URL", "json(https://www.therocktrading.com/api/ticker/BTCEUR).result.0.last");
    }
  }

  function postData() external payable {
    if (oraclize_getPrice("URL") > this.balance) {
      LogNewOraclizeQuery("Oraclize query was NOT sent, please add some ETH to cover for the query fee");
    }
     else {
      LogNewOraclizeQuery("Oraclize query was sent, standing by for the answer..");
      oraclize_query("URL", "json(https://api.postcodes.io/postcodes).status", '{"postcodes" : ["OX49 5NU", "M32 0JG", "NE30 1DP"]}');
    }
  }

  function __callback(bytes32 myid, string result) public {
      require(msg.sender == oraclize_cbAddress());
      LogResult(result);
  }
```

So I want to test this locally, I use the `ethereum-bridge` to deploy `Oraclize`.
The `getResult` result queries works everytime and I get my result. However, the `postData` never works. It just tries to do the query and eventually get timed out in my truffle test.

So I tried to do many many things to find out why it is not working and just some minutes ago I tried to run the ethereum bridge with the `--dev` prop and magically it works. HOW? I don't understand. And also, now that I get `postData` to work with `--dev` prop, the `getResult` stopped working and I get the same initial timeout issue unless I rerun the bridge without `--dev`.

What is going on? From the README.doc it says

> `--dev`: skip contract myid check and pending queries (useful for local testing)

But what is this contract myid skip check and why does it matter in this case?

What config do I need to do both GET and POST request with `Oraclize` on the same eth-bridge?

**Comment by D-Nice** [comment]
Dev mode permits the bridge to be used with ganache/testrpc, which may reset the history of the blockchain and thereby cause reoccurring query ids to occur. Without dev mode, these are normally skipped, to avoid replays on testnets etc... but when used for unit testing with ganache/testrpc that check needs to be disabled, else the queries won't go through, as they've been seen before.

It is quite odd that your getResult query would stop working. I'll see about giving it a try at some point.
