### ISSUE TITLE
Possibility to force query execution before specified delay

### ISSUE THREAD

**Issue by joaopsilva** [oraclize/ethereum-bridge#60]
When running an Oraclize query with a delay (e.g. `oraclize_query(60, "URL", url1)`), it would be useful, in the context of unit tests, to force the `ethereum-bridge` to execute the query before the specified delay.

Otherwise, the delay makes it unfeasible to run automated unit tests when the delay that is specified in the contract is far in the future and immutable.

Moreover, I would have imagined that increasing the timestamp on the EVM would do the trick, but it does not seem to be taken into account by the bridge (running on testrpc). For example, when running the following code snippet, although the current block timestamp is advanced by 60 seconds, the `ethereum-bridge` still waits 60 seconds before executing the query:

```
let currentBlockTime = web3.eth.getBlock(web3.eth.blockNumber).timestamp;
await web3.currentProvider.send({jsonrpc: "2.0", method: "evm_increaseTime", params: [60], id: 0});
await web3.currentProvider.send({jsonrpc: "2.0", method: "evm_mine", params: [], id: 0});
```

Is there a way around this? Thanks in advance.

**Comment by D-Nice** [comment]
The query is executed by the Oraclize engine. All the bridge does is forward any queries it notices on your blockchain with the parameters requested. The blockchain time itself is not taken into account, the engine's own time is used for that. 

If you do need to circumvent this, one thing you could make is a .diff file for production, with the delay enabled, so you can test without the delay.

**Comment by joaopsilva** [comment]
Understood, thanks for the swift reply.
