### ISSUE TITLE
Error: Key not found in database

### ISSUE THREAD

**Issue by perfectmak** [oraclize/ethereum-bridge#65]
My team at [MarketProtocol](https://github.com/MARKETProtocol/MARKETProtocol) are using the ethereum-bridge and while running our test suite which uses ethereum-bridge, ethereum-bridge crashes with the below error:

```
INFO checking HTTP query 46a77f493f30332fb9dced0aa7a6a96c9c2d314bcdc9d963f9675620a5bc71e0 status on Tue Dec 18 2018 17:36:34 GMT-0700 (MST)
Error: Key not found in database
    at Object.InvalidResponse (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as getBlock] (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/method.js:145:58)
    at parseLog (/home/pelsasser/ethereum-bridge/lib/bridge-log-manager.js:130:59)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:120:21
    at Array.forEach (<anonymous>)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:119:32
    at Array.forEach (<anonymous>)
    at Object.onMessage [as callback] (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:117:22)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:259:20
    at Array.forEach (<anonymous>)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:258:12
    at XMLHttpRequest.request.onreadystatechange (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:509:12)
```

Our current best research at this point says there is some asynchronous issues that sometimes occur (more often than not).
We are hoping that you could help provide some insight on how this can be resolved?

### How to reproduce:
We have a reference issue open [here](https://github.com/MARKETProtocol/MARKETProtocol/issues/178) with instruction on how this can be reproduced. It also contains comments on the different approaches we have taken in order to fix this.

**Comment by gskapka** [comment]
Is [this stackexchange](https://ethereum.stackexchange.com/questions/41650/key-not-found-in-database-ethereum-bridge-error/42868) post made by another of our developers of any use?

**Comment by perfectmak** [comment]
@gskapka Thanks it is useful. I'll explore it too

**Comment by D-Nice** [comment]
@perfectmak Did the stackexchange answer help you/is this issue resolved?

**Comment by pelsasser** [comment]
@D-Nice - unfortunately this Stack exchange post doesn't address our issue.  We are not currently running the bridge in `broadcast` mode.

`node bridge -H localhost:9545 -a 9 --dev` is how we typically start the bridge.  Additionally, no amount of time waiting after contract deployment solves the issue when running tests.

**Comment by D-Nice** [comment]
I presume your tests are here? https://github.com/MARKETProtocol/MARKETProtocol

We'll give it a run on our end to see if we can diagnose the issue.

**Comment by D-Nice** [comment]
I've been able to reproduce this error, using our master.

Just some quick notes that may be of use to you but are outside the scope of this issue, I was not able to get your fork of ethereum-bridge to install its dependencies, the fork has not merged some commits that fix these issues, so that may be helpful. You also have the option of installing the bridge via npm, either the regular way, or from a specific github commit.

Also, following the instructions, it install the latest truffle framework, which the repo was not targetted at, may be wise to install via v4 dist-tag (`npm i -g truffle@v4`).

Regarding the above issue, the tests did seem to complete after restarting the bridge, with the last instance. I'll try and figure out what the culprit is here, we use the bridge widely and this is the first occurrence of this arising from truffle tests, without it being invalidly in `broadcast` mode.

**Comment by D-Nice** [comment]
@perfectmak @pelsasser 
Your develop branch tests pass with this patch branch: https://github.com/oraclize/ethereum-bridge/tree/patch-ganache-reset-bug

Someone else from our team should be able to check out the upcoming PR for it this Wednesday I expect, and if no issues, it'll be merged upstream.

**Comment by D-Nice** [comment]
@pelsasser pinging that it's been merged

**Comment by pelsasser** [comment]
works!
