### ISSUE TITLE
Alternative Private Chains

### ISSUE THREAD

**Issue by IamChuancey** [oraclize/ethereum-bridge#73]
That's what I saw on [Oraclize](https://docs.oraclize.it/#integrations-public-chains):
![image](https://user-images.githubusercontent.com/29730996/56903503-08cdf280-6acf-11e9-974b-00ddae8ce61c.png)
 I have trouble in using ethereum-bridge with Oraclize in my private network building by geth.
Does that means Oraclize is not supported in private network by geth, only supported in truffle and testrpc even if I am using ethereum-bridge?

**Comment by D-Nice** [comment]
We'll dedicate someone to investigate if there are some potential issues with Geth. 

The statement is true, as mentioned before, the bridge should work with any EVM network and client exposing RPC via HTTP. The bridge itself is used for a number of the testnets you see. The likelier culprit is a misconfiguration of the network itself, however, we'll still investigate on our end. Could you share your geth version used and genesis file (plaintext please, not screenshots).

**Comment by IamChuancey** [comment]
Yeah, of course.
geth version: `1.8.13-stable`
genesis file:
```
{
    "nonce": "0x0000000000000042",
    "difficulty": "0x020000",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
    "gasLimit": "0xffffffff",
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "alloc": {}
}
```
And my command to start the private network is:
```
geth --networkid 15 --datadir ./data --rpc --rpcapi "admin,debug,eth,miner,net,personal,txpool,web3" --rpcport "8545" --rpccorsdomain "*" 
```

**Comment by D-Nice** [comment]
We've tested the current version of the bridge against geth and parity, and it worked fine, returning a callback as expected. 

An important rule to follow is that the account used for the bridge, should not be used for anything else, especially not deploying your contracts that utilize Provable (Oraclize). 

The bridge was run with `./ethereum-bridge -a 1 -H localhost:8545`

geth was run with `./geth --dev --rpc console`

and some commands were run to create new accounts (as it only has the coinbase by default) and they were funded and unlocked as needed. We used dev to bootstrap a dev chain, that same genesis file can be used to boot strap yours with whatever needed edits.

The culprit in your issue is that running a private chain is not so easy, and the errors you are encountering are unrelated to the bridge itself, but have to do with a misconfiguration of geth or the private chain itself.

**Comment by IamChuancey** [comment]
yes, the error is something about a misconfiguration of geth or the private chain itself. I succeed this morning, with your help,Thank you sincerely!

**Comment by IamChuancey** [comment]
After 3 days and a day morning and thanks to the help from @D-Nice @gskapka , I finally solved the problem.I need to put my thoughts together to help guys who may encounter the same problem.
- only support the `dev` geth private network
I am sorry to say that the oraclize(ethereum-bridge) is only supported the `dev`chain , which means you should start your private network using geth like
```
geth --networkid 15 --datadir ./data --rpc --rpcapi "admin,debug,eth,miner,net,personal,txpool,web3" --rpcport "8545" --rpccorsdomain "*"  --dev
 ```
 or simply, you can start you your private network using 
 ```
geth --dev --rpc console
 ```
- you could deploy the contract using ethereum-bridge in Remix, but you'd better not  interact with the deployed contract using Remix.
Because you will get some error like 
```
gas required exceeds allowance or always failing transaction in private network
``` as there is something wrong with Internal mechanism in Remix.
you should interact with the deployed contract using geth console or web3.js.
Good luck for you!

**Comment by D-Nice** [comment]
Thanks for the answer on that @IamChuancey. To expand on it, the dev flag simply starts a pre-configured network on a geth client, with a certain genesis file. That means one should be able to scrape that genesis file out and should copy some of the core settings, into their private network file, and still have the freedom to set allocations or mining type. However, a misconfigured network may not in fact work, so when you do start configuring your own network, ymmv.
