### ISSUE TITLE
What does this do? 

### ISSUE THREAD

**Issue by maurelian** [oraclize/ethereum-bridge#9]
Hey, this is a great tool, thank you!

Not an issue per se, but it would be helpful to have a better sense of what the various parts of this repo are doing. 

FWIW, I've got it up and running, and importing data to a private chain, but still have a few questions. 

For this purpose, we have a simple contract called `ExchangeRate` that inherits `usingOraclize` and calls `oraclize_query` from the `ExchangeRate.update` method.

* What is the server doing when I send a payment to `ExchangeRate.update`?
* What is a "callback address"?
* What is the "connector"?

Thanks for your help.

**Comment by bertani** [comment]
Hello @maurelian, the reason why we have chosen not to write any extensive tutorial/documentation on the ethereum-bridge tool, is that this is still highly experimental and subject to breaking changes (as specified in the README).
Specifically, we have plans to change a lot the way you would interact with this tool in the coming weeks so please be patient for some more weeks until we roll this out :)

All your questions are around the internal workings of the Oraclize contracts and architecture so its understanding is of limited utility given its wiring-only use. Most of your questions can find an answer by reading [our public Ethereum contracts code here](https://github.com/oraclize/ethereum-api/tree/master/connectors).
* when you call oraclize_query, the connector is called and the Oraclize engine starts computing the relevant answer - which is then sent back to the calling contract 
* the callback address is the address Oraclize uses to send back data to the calling contracts
* the connector is where you find most of the Oraclize onchain logic, it is the gateway to our offchain engine


I hope this helps.

**Comment by maurelian** [comment]
Thanks very much for the response. I appreciate it and understand this is a young tool!

> the callback address is the address Oraclize uses to send back data to the calling contracts

But my callback address is a non-contract account.

So you're sending msg.data to a non-contract account? That's not something I'd considered as useful previously.  There would be no logs generated.  Is `bridge` then reading some data from the transaction receipt?

**Comment by bertani** [comment]
I am not sure I understand your question.

The callback is the transaction Oraclize sends back to the calling contract. Let's say your contract A calls out to Oraclize via oraclize_query. Oraclize will send back the result with a new transaction (the callback one), sent from a given Oraclize account (the callback address) to the calling contract (A).

Does that make sense to you?
